### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by StefMa**
This goes a bit further of #52 and adds dependabot to make sure we are always using the latest versions of dependencies 🙃.

I copied the config from [here](https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/main/.github%2Fdependabot.yml) and removed the dummy auth (because this is not required).

### CODE REVIEW

**Comment by StefMa** [comment]
@ov7a could may have a look? 🙃

**Comment by ov7a** [comment]
@StefMa I'm not sure about this. While having updates is good, I don't feel that the test coverage is strong enough to blindly merge them. And reviewing/testing/managing dependabot PRs usually is annoying.

**Comment by StefMa** [comment]
What types of /more tests would be required to feel save for the current
dependencies (gson)? 🤔

I could also write a few for that.

Beside of that... Gson doesn't get too many updates anymore. The last
update happen a year ago, the one before that 2 years ago 😁

But nevermind, I could also close this PR if you're not interested in it 👍

**Comment by ov7a** [comment]
@StefMa It's not like I'm against it, I just don't feel it's worth it. Let's hear other opinions.

**Pull request closed without merging**
